### ISSUE TITLE
mvn package error

### ISSUE THREAD

**Issue by 2680987** [cjbi/admin3#58]
Failed to execute goal on project admin3-server: Could not resolve dependencies for project tech.wetech.admin3:admin3-server:jar:0.0.1-SNAPSHOT: Could not find artifact tech.wetech.admin3:admin3-ui:jar:0.0.1-SNAPSHOT

**Comment by cjbi** [comment]
在跟目录执行mvn package命令

**Comment by 2680987** [comment]
根目录执行如下错误
[INFO] Reactor Summary for admin3-parent 0.0.1-SNAPSHOT:
[INFO]
[INFO] admin3-ui .......................................... SUCCESS [ 54.357 s]
[INFO] admin3-server ...................................... FAILURE [  7.340 s]
[INFO] admin3-parent ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:02 min
[INFO] Finished at: 2023-02-12T06:56:42+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.0.1:repackage (repackage) on project admin3-server: Execution repackage of goal org.springframework.boot:spring-boot-maven-plugin:3.0.1:repackage failed: Plugin org.springframework.boot:spring-boot-maven-plugin:3.0.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.springframework.boot:spring-boot-maven-plugin:jar:3.0.1 -> org.springframework.boot:spring-boot-buildpack-platform:jar:3.0.1: Failed to read artifact descriptor for org.springframework.boot:spring-boot-buildpack-platform:jar:3.0.1: Could not transfer artifact org.springframework.boot:spring-boot-buildpack-platform:pom:3.0.1 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/127.0.1.2] failed: Connection refused: no further information -> [Help 1]

**Comment by 2680987** [comment]
用阿里镜像也不行
	<mirror>
		<id>alimaven</id>
		<name>aliyun maven</name>
		<url>http://maven.aliyun.com/nexus/content/groups/public/</url>
		<mirrorOf>central</mirrorOf>       

	</mirror>
错误如下

[INFO] Scanning for projects...
Downloading from alimaven: http://maven.aliyun.com/nexus/content/groups/public/org/springframework/boot/spring-boot-starter-parent/3.0.1/spring-boot-starter-parent-3.0.1.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for tech.wetech.admin3:admin3-server:0.0.1-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:3.0.1 from/to alimaven (http://maven.aliyun.com/nexus/content/groups/public/): Connect to maven.aliyun.com:80 [maven.aliyun.com/127.0.1.2] failed: Connection refused: no further information and 'parent.relativePath' points at no local POM @ line 5, column 11

**Comment by cjbi** [comment]
可能是Maven 中央仓库网络问题，阿里云有时候也会受影响，换个时间段或者换个网络环境再试试看

**Comment by 2680987** [comment]
部署成功，可是 登录失败
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.3.jar!/:6.0.3]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-6.0.3.jar!/:6.0.3]
        ... 73 common frames omitted
Caused by: java.sql.SQLException: Incorrect string value: '\xB9\xDC\xC0\xED\xD4\xB1...' for column 'data' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-j-8.0.31.jar!/:8.0.31]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.31.jar!/:8.0.31]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916) ~[mysql-connector-j-8.0.31.jar!/:8.0.31]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-j-8.0.31.jar!/:8.0.31]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-j-8.0.31.jar!/:8.0.31]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-c

**Comment by 2680987** [comment]
数据库连接串
3306/admin3?useUnicode=true&characterEncoding=UTF-8

**Comment by cjbi** [comment]
试试在启动命令加环境参数`-Dfile.encoding=UTF-8`，应该能解决

**Comment by 2680987** [comment]
可以了，谢谢
