### ISSUE TITLE
native docker 镜像无法启动

### ISSUE THREAD

**Issue by aircjm** [cjbi/admin3#81]
我这边测试native镜像并没有成功，可以直接通过mysql -h host地址远程连接所以应该不是网络连接问题。

这个是我使用的脚本
```
docker run -p 8082:8080 -e JAVA_OPTS="-Dfile.encoding=UTF-8 -Duser.timezone=GMT+8 -Dspring.jpa.hibernate.ddl-auto=create -Dspring.datasource.url=jdbc:mysql://domain.com:3306/admin?useUnicode=true&characterEncoding=utf-8 -Dspring.datasource.username=root -Dspring.datasource.password=123456 -Dspring.jpa.database-platform=org.hibernate.dialect.MySQLDialect" -e SPRING_DATASOURCE_URL="jdbc:mysql://domain.com:3306/admin?useUnicode=true&characterEncoding=utf-8" -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWOERD=123456 --name admin3 cjbi/admin3-native:latest
```

错误日志见：
```
2023-07-09T13:44:08.106Z  INFO 1 --- [           main] t.wetech.admin3.Admin3ServerApplication  : Starting AOT-processed Admin3ServerApplication using Java 17.0.7 with PID 1 (/workspace/tech.wetech.admin3.Admin3ServerApplication started by cnb in /workspace)
2023-07-09T13:44:08.106Z  INFO 1 --- [           main] t.wetech.admin3.Admin3ServerApplication  : The following 1 profile is active: "biz"
2023-07-09T13:44:08.139Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-07-09T13:44:08.140Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-07-09T13:44:08.141Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.4]
2023-07-09T13:44:08.149Z  INFO 1 --- [           main] o.a.c.c.C.[.[localhost].[/admin3]        : Initializing Spring embedded WebApplicationContext
2023-07-09T13:44:08.149Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 42 ms
2023-07-09T13:44:08.169Z  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2023-07-09T13:44:08.171Z  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.1.6.Final
2023-07-09T13:44:08.173Z  WARN 1 --- [           main] org.hibernate.orm.deprecation            : HHH90000021: Encountered deprecated setting [javax.persistence.sharedCache.mode], use [jakarta.persistence.sharedCache.mode] instead
2023-07-09T13:44:08.177Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2023-07-09T13:44:09.190Z ERROR 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

java.sql.SQLException: Access denied for user 'root'@'172.23.0.3' (using password: YES)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[na:na]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[na:na]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[tech.wetech.admin3.Admin3ServerApplication:8.0.31]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[tech.wetech.admin3.Admin3ServerApplication:8.0.31]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[tech.wetech.admin3.Admin3ServerApplication:8.0.31]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[tech.wetech.admin3.Admin3ServerApplication:8.0.31]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[na:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[tech.wetech.admin3.Admin3ServerApplication:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[tech.wetech.admin3.Admin3ServerApplication:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[na:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[na:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[na:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[tech.wetech.admin3.Admin3ServerApplication:na]
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[na:na]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:284) ~[na:na]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:177) ~[na:na]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:36) ~[na:na]
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:119) ~[na:na]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:255) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:230) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:207) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.boot.model.relational.Database.<init>(Database.java:44) ~[na:na]
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:218) ~[na:na]
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:191) ~[na:na]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:138) ~[na:na]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1350) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1421) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66) ~[na:na]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1130) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:905) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at tech.wetech.admin3.Admin3ServerApplication.main(Admin3ServerApplication.java:12) ~[tech.wetech.admin3.Admin3ServerApplication:na]

2023-07-09T13:44:09.192Z  WARN 1 --- [           main] o.h.e.j.e.i.JdbcEnvironmentInitiator     : HHH000342: Could not obtain connection to query metadata

java.sql.SQLException: Access denied for user 'root'@'172.23.0.3' (using password: YES)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[na:na]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[na:na]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[tech.wetech.admin3.Admin3ServerApplication:8.0.31]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[tech.wetech.admin3.Admin3ServerApplication:8.0.31]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[tech.wetech.admin3.Admin3ServerApplication:8.0.31]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[tech.wetech.admin3.Admin3ServerApplication:8.0.31]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[na:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[tech.wetech.admin3.Admin3ServerApplication:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[tech.wetech.admin3.Admin3ServerApplication:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[na:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[na:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[na:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[tech.wetech.admin3.Admin3ServerApplication:na]
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[na:na]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:284) ~[na:na]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:177) ~[na:na]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:36) ~[na:na]
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:119) ~[na:na]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:255) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:230) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:207) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.boot.model.relational.Database.<init>(Database.java:44) ~[na:na]
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:218) ~[na:na]
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:191) ~[na:na]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:138) ~[na:na]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1350) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1421) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66) ~[na:na]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1130) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:905) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at tech.wetech.admin3.Admin3ServerApplication.main(Admin3ServerApplication.java:12) ~[tech.wetech.admin3.Admin3ServerApplication:na]

2023-07-09T13:44:09.193Z ERROR 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
2023-07-09T13:44:09.193Z  WARN 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
2023-07-09T13:44:09.193Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-07-09T13:44:09.195Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1130) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:905) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[tech.wetech.admin3.Admin3ServerApplication:3.0.1]
        at tech.wetech.admin3.Admin3ServerApplication.main(Admin3ServerApplication.java:12) ~[tech.wetech.admin3.Admin3ServerApplication:na]
Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:267) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:230) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:207) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.boot.model.relational.Database.<init>(Database.java:44) ~[na:na]
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:218) ~[na:na]
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:191) ~[na:na]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:138) ~[na:na]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1350) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1421) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:66) ~[na:na]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[tech.wetech.admin3.Admin3ServerApplication:6.0.3]
        ... 16 common frames omitted
Caused by: org.hibernate.HibernateException: Unable to determine Dialect without JDBC metadata (please set 'javax.persistence.jdbc.url', 'hibernate.connection.url', or 'hibernate.dialect')
        at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:147) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:60) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:244) ~[na:na]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:36) ~[na:na]
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:119) ~[na:na]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:255) ~[tech.wetech.admin3.Admin3ServerApplication:6.1.6.Final]
        ... 31 common frames omitted
```

**Comment by cjbi** [comment]
你这个host，换成ip再试试
